name: wsipre
channels:
  - defaults
dependencies:
  - ca-certificates=2018.03.07=0
  - certifi=2018.10.15=py37_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - ncurses=6.1=he6710b0_1
  - openssl=1.1.1a=h7b6447c_0
  - pip=18.1=py37_0
  - python=3.7.1=h0371630_3
  - readline=7.0=h7b6447c_5
  - setuptools=40.6.2=py37_0
  - sqlite=3.25.3=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.32.3=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - alabaster==0.7.12
    - babel==2.6.0
    - backcall==0.1.0
    - bleach==3.0.2
    - chardet==3.0.4
    - click==7.0
    - cloudpickle==0.6.1
    - cycler==0.10.0
    - dask==1.0.0
    - decorator==4.3.0
    - defusedxml==0.5.0
    - docutils==0.14
    - entrypoints==0.2.3
    - idna==2.7
    - imagesize==1.1.0
    - ipykernel==5.1.0
    - ipython==7.2.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.4.2
    - jedi==0.13.1
    - jinja2==2.10
    - jsonschema==2.6.0
    - jupyter==1.0.0
    - jupyter-client==5.2.3
    - jupyter-console==6.0.0
    - jupyter-core==4.4.0
    - kiwisolver==1.0.1
    - livereload==2.6.0
    - markdown==3.0.1
    - markupsafe==1.1.0
    - matplotlib==3.0.2
    - mistune==0.8.4
    - nbconvert==5.4.0
    - nbformat==4.4.0
    - networkx==2.2
    - notebook==5.7.2
    - numpy==1.15.4
    - numpydoc==0.8.0
    - opencv-python==3.4.4.19
    - openslide-python==1.1.1
    - packaging==18.0
    - pandocfilters==1.4.2
    - parso==0.3.1
    - pexpect==4.6.0
    - pickleshare==0.7.5
    - pillow==5.3.0
    - prometheus-client==0.4.2
    - prompt-toolkit==2.0.7
    - ptyprocess==0.6.0
    - pygments==2.3.0
    - pyparsing==2.3.0
    - python-dateutil==2.7.5
    - pytz==2018.7
    - pywavelets==1.0.1
    - pyyaml==3.13
    - pyzmq==17.1.2
    - qtconsole==4.4.3
    - requests==2.20.1
    - scikit-image==0.14.1
    - scipy==1.1.0
    - send2trash==1.5.0
    - six==1.11.0
    - snowballstemmer==1.2.1
    - sphinx==1.8.2
    - sphinx-better-theme==0.1.5
    - sphinxcontrib-websupport==1.1.0
    - terminado==0.8.1
    - testpath==0.4.2
    - toolz==0.9.0
    - tornado==5.1.1
    - traitlets==4.3.2
    - urllib3==1.24.1
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - widgetsnbextension==3.4.2
prefix: /home/luis/anaconda3/envs/wsipre

